"use strict";

// Stable IPC contract shared by the main process and every preload.
// Keeping channel names here prevents silent drift while bundled modules are
// replaced with maintainable source one subsystem at a time.
const IPC = Object.freeze({
  ISLAND_NOTCH_INFO: "island:notch-info",
  ISLAND_SESSION_UPDATE: "island:session-update",
  ISLAND_PRESENT_SURFACE: "island:present-surface",
  ISLAND_QUOTA_UPDATE: "island:quota-update",
  ISLAND_ENTER: "island:enter",
  ISLAND_LEAVE: "island:leave",
  ISLAND_FILE_DRAG_STATE: "island:file-drag-state",
  ISLAND_OPEN_SETTINGS: "island:open-settings",
  ISLAND_OPEN_SETTINGS_TAB: "island:open-settings-tab",
  ISLAND_TOGGLE_SOUND: "island:toggle-sound",
  ISLAND_SOUND_STATE: "island:sound-state",
  ISLAND_HAPTIC: "island:haptic",
  ISLAND_OPEN_ABOUT: "island:open-about",
  ISLAND_TOGGLE_EXPAND: "island:toggle-expand",
  ISLAND_COLLAPSE: "island:collapse",
  ISLAND_SURFACE_DISMISSED: "island:surface-dismissed",
  ISLAND_PANEL_EXPANDED: "island:panel-expanded",
  ISLAND_PANEL_COLLAPSED: "island:panel-collapsed",
  ISLAND_INTERACTION_BOUNDS: "island:interaction-bounds",
  ISLAND_WINDOW_BLUR: "island:window-blur",
  ISLAND_FOCUS_LOSS_HIDE: "island:focus-loss-hide",
  ISLAND_SYNC_CLOSED_WINDOW: "island:sync-closed-window",
  // floating 模式拖动：渲染层按下并上报位移，主进程移动窗口；松手时贴边吸附。
  ISLAND_DRAG_START: "island:drag-start",
  ISLAND_DRAG_END: "island:drag-end",
  ISLAND_PLACEMENT: "island:placement",
  ISLAND_GET_PLACEMENT: "island:get-placement",
  ISLAND_DRAG_TO_PET: "island:drag-to-pet",
  ISLAND_TODAY_BURN_UPDATE: "island:today-burn-update",
  ISLAND_RESIZE: "island:resize",
  ISLAND_SWITCH_SESSION: "island:switch-session",
  ISLAND_CONFIRM_SESSION: "island:confirm-session",
  ISLAND_UNDO_SETTINGS_CHANGES: "island:undo-settings-changes",
  ISLAND_GET_AGENT_SETUP_STATUS: "island:get-agent-setup-status",

  MEDIA_GET_STATE: "media:get-state",
  MEDIA_STATE_UPDATE: "media:state-update",
  MEDIA_COMMAND: "media:command",
  LYRICS_GET_STATE: "lyrics:get-state",
  LYRICS_STATE_UPDATE: "lyrics:state-update",
  LYRICS_CLEAR_CACHE: "lyrics:clear-cache",
  PERFORMANCE_GET_STATE: "performance:get-state",
  PERFORMANCE_STATE_UPDATE: "performance:state-update",
  PERFORMANCE_DETAILS_VISIBLE: "performance:details-visible",
  PERFORMANCE_PROCESS_ACTION: "performance:process-action",

  SHELF_GET_STATE: "shelf:get-state",
  SHELF_STATE_UPDATE: "shelf:state-update",
  SHELF_GET_PREVIEW: "shelf:get-preview",
  SHELF_ADD_PATHS: "shelf:add-paths",
  SHELF_NATIVE_DROP_RESULT: "shelf:native-drop-result",
  SHELF_ADD_PAYLOAD: "shelf:add-payload",
  SHELF_REMOVE: "shelf:remove",
  SHELF_CLEAR: "shelf:clear",
  SHELF_OPEN: "shelf:open",
  SHELF_REVEAL: "shelf:reveal",
  SHELF_QUICK_LOOK: "shelf:quick-look",
  SHELF_START_DRAG: "shelf:start-drag",
  SHELF_PASTE_FROM_CLIPBOARD: "shelf:paste-from-clipboard",
  SHELF_COPY_ITEMS: "shelf:copy-items",
  SHELF_SHARE_ITEMS: "shelf:share-items",
  SHELF_GET_SHARE_PROVIDERS: "shelf:get-share-providers",
  SHELF_SET_QUICK_SHARE_PROVIDER: "shelf:set-quick-share-provider",
  SHELF_SHARE_VIA_DEFAULT: "shelf:share-via-default",
  SHELF_GET_AIRDROP_ICON: "shelf:get-airdrop-icon",
  SHELF_SHARE_AIRDROP: "shelf:share-airdrop",
  SHELF_SHARE_DROP_BOUNDS: "shelf:share-drop-bounds",

  CLIPBOARD_HISTORY_GET_STATE: "clipboard-history:get-state",
  CLIPBOARD_HISTORY_UPDATE: "clipboard-history:update",
  CLIPBOARD_HISTORY_REPLAY: "clipboard-history:replay",
  CLIPBOARD_HISTORY_FAVORITE: "clipboard-history:favorite",
  CLIPBOARD_HISTORY_REMOVE: "clipboard-history:remove",
  CLIPBOARD_HISTORY_CLEAR: "clipboard-history:clear",

  TERMINAL_GET_STATE: "terminal:get-state",
  TERMINAL_STATUS_UPDATE: "terminal:status-update",
  TERMINAL_DATA: "terminal:data",
  TERMINAL_START: "terminal:start",
  TERMINAL_INPUT: "terminal:input",
  TERMINAL_RESIZE: "terminal:resize",
  TERMINAL_RESTART: "terminal:restart",
  TERMINAL_STOP: "terminal:stop",
  TERMINAL_RUN_SAVED_COMMAND: "terminal:run-saved-command",
  TERMINAL_INTERACTIVE_CHANGED: "terminal:interactive-changed",

  SETTINGS_SELECT_DIRECTORY: "settings:select-directory",

  PET_ENTER: "pet:enter",
  PET_LEAVE: "pet:leave",
  PET_DRAG_TO_ISLAND: "pet:drag-to-island",
  PET_RETURN_TO_ISLAND: "pet:return-to-island",
  PET_MOVE: "pet:move",
  PET_READY: "pet:ready",
  PET_SESSION_UPDATE: "pet:session-update",
  PET_CLICK: "pet:click",
  PET_TOGGLE_PANEL: "pet:toggle-panel",
  PET_PANEL_STATE: "pet:panel-state",
  PET_PANEL_INIT: "pet-panel:init",
  PET_PANEL_READY: "pet-panel:ready",
  PET_PANEL_RESIZE: "pet-panel:resize",
  PET_PANEL_SURFACE: "pet-panel:surface",
  PET_PANEL_COLLAPSE: "pet-panel:collapse",
  PET_SIZE_UPDATE: "pet:size-update",
  PET_TODAY_BURN_UPDATE: "pet:today-burn-update",
  PET_GET_SPRITE_PATH: "pet:get-sprite-path",
  PET_OPEN_SPRITES_DIR: "pet:open-sprites-dir",
  PET_TOGGLE: "pet:toggle",

  APPEARANCE_GET_BACKGROUND_IMAGE: "appearance:get-background-image",
  APPEARANCE_SELECT_BACKGROUND_IMAGE: "appearance:select-background-image",
  APPEARANCE_INSTALL_BACKGROUND_IMAGE: "appearance:install-background-image",

  TEMPLATE_GET_ACTIVE_STATUS_ASSETS: "template:get-active-status-assets",
  TEMPLATE_LIST: "template:list",

  WELCOME_GET_STARTED: "welcome:get-started",
  WELCOME_GET_FIRST_LAUNCH_AT: "welcome:get-first-launch-at",
  ISLAND_ONBOARDING_EXPAND: "island:onboarding-expand",

  SESSION_APPROVE: "session:approve",
  SESSION_DENY: "session:deny",
  SESSION_ANSWER: "session:answer",
  SESSION_CANCEL_QUESTION: "session:cancel-question",
  SESSION_CONFIRM_PLAN: "session:confirm-plan",
  SESSION_JUMP: "session:jump",
  SESSION_DELETE: "session:delete",
  SESSION_DELETE_BATCH: "session:delete-batch",
  SESSION_DISMISS_COMPLETION: "session:dismiss-completion",
  SESSION_CONTINUE_VIA_TERMINAL_PROMPT: "session:continue-via-terminal-prompt",

  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SETTINGS_GET_TELEMETRY_STATUS: "settings:get-telemetry-status",
  SETTINGS_DID_CHANGE: "settings:did-change",
  SETTINGS_GET_HOOK_STATUS: "settings:get-hook-status",
  SETTINGS_INSTALL_HOOK: "settings:install-hook",
  SETTINGS_UNINSTALL_HOOK: "settings:uninstall-hook",
  SETTINGS_UNINSTALL_ALL_HOOKS: "settings:uninstall-all-hooks",
  SETTINGS_REPAIR_HOOK: "settings:repair-hook",
  SETTINGS_REPAIR_ALL_HOOKS: "settings:repair-all-hooks",
  SETTINGS_GET_DOCTOR_AUDIT: "settings:get-doctor-audit",
  SETTINGS_GET_DISPLAYS: "settings:get-displays",
  SETTINGS_GET_CODEX_PETS: "settings:get-codex-pets",
  SETTINGS_PREVIEW_SOUND: "settings:preview-sound",
  SETTINGS_OPEN_SOUNDS_DIR: "settings:open-sounds-dir",
  SETTINGS_GET_CUSTOM_ICON: "settings:get-custom-icon",
  SETTINGS_SELECT_CUSTOM_ICON: "settings:select-custom-icon",
  SETTINGS_RESET_CUSTOM_ICON: "settings:reset-custom-icon",
  CUSTOM_ICON_CHANGED: "custom-icon:changed",
  SETTINGS_COPY_IMAGE_TO_CLIPBOARD: "settings:copy-image-to-clipboard",
  SETTINGS_COPY_IMAGE_DATA_URL_TO_CLIPBOARD: "settings:copy-image-data-url-to-clipboard",
  SETTINGS_SHORTCUT_STATUS: "settings:shortcut-status",
  SETTINGS_GET_SHORTCUT_STATUS: "settings:get-shortcut-status",
  SETTINGS_GET_AGENT_CONTROL_STATUS: "settings:get-agent-control-status",
  SETTINGS_CONNECT_AGENT_CONTROL_CLIENT: "settings:connect-agent-control-client",
  SETTINGS_DISCONNECT_AGENT_CONTROL_CLIENT: "settings:disconnect-agent-control-client",
  SETTINGS_GET_AGENT_CONTROL_MANUAL_CONFIG: "settings:get-agent-control-manual-config",

  REMOTE_HOSTS_GET_STATE: "remote-hosts:get-state",
  REMOTE_HOSTS_CREATE_TOKEN: "remote-hosts:create-token",
  REMOTE_HOSTS_REVOKE: "remote-hosts:revoke",
  REMOTE_HOSTS_SCAN_SSH_CONFIG: "remote-hosts:scan-ssh-config",
  REMOTE_HOSTS_INVITE: "remote-hosts:invite",
  REMOTE_HOSTS_START_TUNNEL: "remote-hosts:start-tunnel",

  LOCALE_GET_STATE: "locale:get-state",
  LOCALE_SET_PREFERENCE: "locale:set-preference",
  LOCALE_DID_CHANGE: "locale:did-change",
  APP_QUIT: "app:quit",
  APP_OPEN_EXTERNAL: "app:open-external",
  APP_CHECK_FOR_UPDATES: "app:check-for-updates",
  APP_UPDATE_AVAILABLE: "app:update-available",
  APP_UPDATE_DOWNLOAD: "app:update-download",
  APP_UPDATE_INSTALL: "app:update-install",
  APP_UPDATE_STATE: "app:update-state",
  USAGE_GET_QUOTA: "usage:get-quota",
  USAGE_GET_QUOTA_MAP: "usage:get-quota-map",
  USAGE_GET_SUMMARY: "usage:get-summary",
  USAGE_GET_SESSION_INSIGHTS: "usage:get-session-insights",
  USAGE_EXPORT_DATA: "usage:export-data",
  USAGE_CLEAR_DATA: "usage:clear-data",
  STATS_GET_SNAPSHOT: "stats:get-snapshot",

  DEBUG_GET_STATUS: "debug:get-status",
  DEBUG_RESET_ONBOARDING: "debug:reset-onboarding",
  SETTINGS_NAVIGATE_TO_TAB: "settings:navigate-to-tab",
  GET_APP_VERSION: "app:get-version",

  COLLECT_LOGS: "diagnostics:collect-logs",
  PLUGIN_AGENT_META: "plugin:agent-meta"
});

module.exports = { IPC };
