"use strict";

// Stable IPC contract shared by the main process and every preload.
// Keeping channel names here prevents silent drift while bundled modules are
// replaced with maintainable source one subsystem at a time.
const IPC = Object.freeze({
  ISLAND_NOTCH_INFO: "island:notch-info",
  ISLAND_SESSION_UPDATE: "island:session-update",
  ISLAND_PRESENT_SURFACE: "island:present-surface",
  ISLAND_QUOTA_UPDATE: "island:quota-update",
  ISLAND_ENTER: "island:enter",
  ISLAND_LEAVE: "island:leave",
  ISLAND_OPEN_SETTINGS: "island:open-settings",
  ISLAND_OPEN_SETTINGS_TAB: "island:open-settings-tab",
  ISLAND_TOGGLE_SOUND: "island:toggle-sound",
  ISLAND_SOUND_STATE: "island:sound-state",
  ISLAND_HAPTIC: "island:haptic",
  ISLAND_OPEN_ABOUT: "island:open-about",
  ISLAND_TOGGLE_EXPAND: "island:toggle-expand",
  ISLAND_COLLAPSE: "island:collapse",
  ISLAND_SURFACE_DISMISSED: "island:surface-dismissed",
  ISLAND_PANEL_EXPANDED: "island:panel-expanded",
  ISLAND_PANEL_COLLAPSED: "island:panel-collapsed",
  ISLAND_WINDOW_BLUR: "island:window-blur",
  ISLAND_FOCUS_LOSS_HIDE: "island:focus-loss-hide",
  ISLAND_SYNC_CLOSED_WINDOW: "island:sync-closed-window",
  // floating 模式拖动：渲染层按下并上报位移，主进程移动窗口；松手时贴边吸附。
  ISLAND_DRAG_START: "island:drag-start",
  ISLAND_DRAG_MOVE: "island:drag-move",
  ISLAND_DRAG_END: "island:drag-end",
  ISLAND_PLACEMENT: "island:placement",
  ISLAND_GET_PLACEMENT: "island:get-placement",
  ISLAND_DRAG_TO_PET: "island:drag-to-pet",
  ISLAND_TODAY_BURN_UPDATE: "island:today-burn-update",
  ISLAND_RESIZE: "island:resize",
  ISLAND_SWITCH_SESSION: "island:switch-session",
  ISLAND_CONFIRM_SESSION: "island:confirm-session",

  PET_ENTER: "pet:enter",
  PET_LEAVE: "pet:leave",
  PET_DRAG_TO_ISLAND: "pet:drag-to-island",
  PET_RETURN_TO_ISLAND: "pet:return-to-island",
  PET_MOVE: "pet:move",
  PET_READY: "pet:ready",
  PET_SESSION_UPDATE: "pet:session-update",
  PET_CLICK: "pet:click",
  PET_TOGGLE_PANEL: "pet:toggle-panel",
  PET_PANEL_STATE: "pet:panel-state",
  PET_PANEL_INIT: "pet-panel:init",
  PET_PANEL_READY: "pet-panel:ready",
  PET_PANEL_RESIZE: "pet-panel:resize",
  PET_PANEL_SURFACE: "pet-panel:surface",
  PET_SIZE_UPDATE: "pet:size-update",
  PET_TODAY_BURN_UPDATE: "pet:today-burn-update",
  PET_GET_SPRITE_PATH: "pet:get-sprite-path",
  PET_OPEN_SPRITES_DIR: "pet:open-sprites-dir",
  PET_TOGGLE: "pet:toggle",

  WELCOME_GET_STARTED: "welcome:get-started",
  WELCOME_GET_FIRST_LAUNCH_AT: "welcome:get-first-launch-at",
  ISLAND_ONBOARDING_EXPAND: "island:onboarding-expand",

  SESSION_APPROVE: "session:approve",
  SESSION_DENY: "session:deny",
  SESSION_ANSWER: "session:answer",
  SESSION_CANCEL_QUESTION: "session:cancel-question",
  SESSION_CONFIRM_PLAN: "session:confirm-plan",
  SESSION_JUMP: "session:jump",
  SESSION_DELETE: "session:delete",
  SESSION_DELETE_BATCH: "session:delete-batch",
  SESSION_DISMISS_COMPLETION: "session:dismiss-completion",
  SESSION_CONTINUE_VIA_TERMINAL_PROMPT: "session:continue-via-terminal-prompt",

  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SETTINGS_DID_CHANGE: "settings:did-change",
  SETTINGS_GET_HOOK_STATUS: "settings:get-hook-status",
  SETTINGS_INSTALL_HOOK: "settings:install-hook",
  SETTINGS_UNINSTALL_HOOK: "settings:uninstall-hook",
  SETTINGS_UNINSTALL_ALL_HOOKS: "settings:uninstall-all-hooks",
  SETTINGS_GET_DISPLAYS: "settings:get-displays",
  SETTINGS_GET_CODEX_PETS: "settings:get-codex-pets",
  SETTINGS_PREVIEW_SOUND: "settings:preview-sound",
  SETTINGS_OPEN_SOUNDS_DIR: "settings:open-sounds-dir",
  SETTINGS_GET_CUSTOM_ICON: "settings:get-custom-icon",
  SETTINGS_SELECT_CUSTOM_ICON: "settings:select-custom-icon",
  SETTINGS_RESET_CUSTOM_ICON: "settings:reset-custom-icon",
  CUSTOM_ICON_CHANGED: "custom-icon:changed",
  SETTINGS_COPY_IMAGE_TO_CLIPBOARD: "settings:copy-image-to-clipboard",
  SETTINGS_COPY_IMAGE_DATA_URL_TO_CLIPBOARD: "settings:copy-image-data-url-to-clipboard",
  SETTINGS_SHORTCUT_STATUS: "settings:shortcut-status",
  SETTINGS_GET_SHORTCUT_STATUS: "settings:get-shortcut-status",

  GET_LOCALE: "locale:get",
  SET_LOCALE: "locale:set",
  APP_QUIT: "app:quit",
  APP_OPEN_EXTERNAL: "app:open-external",
  USAGE_GET_QUOTA: "usage:get-quota",
  USAGE_GET_QUOTA_MAP: "usage:get-quota-map",
  STATS_GET_SNAPSHOT: "stats:get-snapshot",

  DEBUG_GET_STATUS: "debug:get-status",
  DEBUG_RESET_ONBOARDING: "debug:reset-onboarding",
  SETTINGS_NAVIGATE_TO_TAB: "settings:navigate-to-tab",
  GET_APP_VERSION: "app:get-version",

  COLLECT_LOGS: "diagnostics:collect-logs",
  PLUGIN_AGENT_META: "plugin:agent-meta"
});

module.exports = { IPC };
